version: 2.1

jobs:
  checkoutAndTest:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  integrateFrontend:
    machine: true
    steps:
     - run: git clone https://github.com/frabla23/frank-tp2-backend.git
     - run: git clone https://github.com/frabla23/frank-tp2-frontend.git
     - run: cd frank-tp2-frontend && npm i
     - run: cd frank-tp2-frontend && npm run build
     - run: cd frank-tp2-backend && mkdir public
     - run: cp -rT frank-tp2-frontend/build frank-tp2-backend/public
     - persist_to_workspace:
               root: .
               paths:
                 - frank-tp2-backend
  deploy:
    machine: true
    steps:
     - attach_workspace:
               at: .
     - run: ls -R1

workflows:
  build:
    jobs:
      - checkoutAndTest
      - integrateFrontend:
          requires:
            - checkoutAndTest
      - deploy:
          requires:
            - integrateFrontend
